BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "nobels" (
	"name"	TEXT,
	"gender"	TEXT,
	"category"	TEXT,
	"year"	INTEGER
);
INSERT INTO "nobels" VALUES ('André Paul Guillaume Gide','male','Literature',1947);
INSERT INTO "nobels" VALUES ('Arthur Ashkin','male','Physics',2018);
INSERT INTO "nobels" VALUES ('Gérard Mourou','male','Physics',2018);
INSERT INTO "nobels" VALUES ('Donna Strickland','female','Physics',2018);
INSERT INTO "nobels" VALUES ('Andrea Ghez','female','Physics',2020);
INSERT INTO "nobels" VALUES ('Roger Penrose','male','Physics',2020);
INSERT INTO "nobels" VALUES ('Reinhard Genzel','male','Physics',2020);
INSERT INTO "nobels" VALUES ('Alfred G. Gilman','male','Physiology_or_Medicine',1994);
INSERT INTO "nobels" VALUES ('Martin Rodbell','male','Physiology_or_Medicine',1994);
INSERT INTO "nobels" VALUES ('Earl (Bertrand Arthur William) Russell','male','Literature',1950);
INSERT INTO "nobels" VALUES ('Barack Hussein Obama','male','Peace',2009);
INSERT INTO "nobels" VALUES ('Charles Thomson Rees Wilson','male','Physics',1927);
INSERT INTO "nobels" VALUES ('Arthur Holly Compton','male','Physics',1927);
INSERT INTO "nobels" VALUES ('Albert Schweitzer','male','Peace',1952);
INSERT INTO "nobels" VALUES ('Albert Arnold (Al) Gore Jr.','male','Peace',2007);
INSERT INTO "nobels" VALUES ('Charles Brenton Huggins','male','Physiology_or_Medicine',1966);
INSERT INTO "nobels" VALUES ('Peyton Rous','male','Physiology_or_Medicine',1966);
INSERT INTO "nobels" VALUES ('Christian B. Anfinsen','male','Chemistry',1972);
INSERT INTO "nobels" VALUES ('Stanford Moore','male','Chemistry',1972);
INSERT INTO "nobels" VALUES ('William H. Stein','male','Chemistry',1972);
INSERT INTO "nobels" VALUES ('Carl Ferdinand Cori','male','Physiology_or_Medicine',1947);
INSERT INTO "nobels" VALUES ('Bernardo Alberto Houssay','male','Physiology_or_Medicine',1947);
INSERT INTO "nobels" VALUES ('Gerty Theresa Cori, née Radnitz','female','Physiology_or_Medicine',1947);
INSERT INTO "nobels" VALUES ('Archer John Porter Martin','male','Chemistry',1952);
INSERT INTO "nobels" VALUES ('Richard Laurence Millington Synge','male','Chemistry',1952);
INSERT INTO "nobels" VALUES ('Adolfo Pérez Esquivel','male','Peace',1980);
INSERT INTO "nobels" VALUES ('Burton Richter','male','Physics',1976);
INSERT INTO "nobels" VALUES ('Samuel Chao Chung Ting','male','Physics',1976);
INSERT INTO "nobels" VALUES ('Andre Geim','male','Physics',2010);
INSERT INTO "nobels" VALUES ('Konstantin Novoselov','male','Physics',2010);
INSERT INTO "nobels" VALUES ('Alexis Carrel','male','Physiology_or_Medicine',1912);
INSERT INTO "nobels" VALUES ('Angus Deaton','male','Economic_Sciences',2015);
INSERT INTO "nobels" VALUES ('Adam G. Riess','male','Physics',2011);
INSERT INTO "nobels" VALUES ('Brian P. Schmidt','male','Physics',2011);
INSERT INTO "nobels" VALUES ('Saul Perlmutter','male','Physics',2011);
INSERT INTO "nobels" VALUES ('Clifford G. Shull','male','Physics',1994);
INSERT INTO "nobels" VALUES ('Bertram N. Brockhouse','male','Physics',1994);
INSERT INTO "nobels" VALUES ('Arno Allan Penzias','male','Physics',1978);
INSERT INTO "nobels" VALUES ('Pyotr Leonidovich Kapitsa','male','Physics',1978);
INSERT INTO "nobels" VALUES ('Robert Woodrow Wilson','male','Physics',1978);
INSERT INTO "nobels" VALUES ('Charles Albert Gobat','male','Peace',1902);
INSERT INTO "nobels" VALUES ('Élie Ducommun','male','Peace',1902);
INSERT INTO "nobels" VALUES ('Anthony J. Leggett','male','Physics',2003);
INSERT INTO "nobels" VALUES ('Alexei Alexeyevich Abrikosov','male','Physics',2003);
INSERT INTO "nobels" VALUES ('Vitaly Lazarevich Ginzburg','male','Physics',2003);
INSERT INTO "nobels" VALUES ('A. Michael Spence','male','Economic_Sciences',2001);
INSERT INTO "nobels" VALUES ('George A. Akerlof','male','Economic_Sciences',2001);
INSERT INTO "nobels" VALUES ('Joseph E. Stiglitz','male','Economic_Sciences',2001);
INSERT INTO "nobels" VALUES ('Bertil Ohlin','male','Economic_Sciences',1977);
INSERT INTO "nobels" VALUES ('James E. Meade','male','Economic_Sciences',1977);
INSERT INTO "nobels" VALUES ('Amartya Sen','male','Economic_Sciences',1998);
INSERT INTO "nobels" VALUES ('Charles Robert Richet','male','Physiology_or_Medicine',1913);
INSERT INTO "nobels" VALUES ('Baroness Bertha Sophie Felicita von Suttner, née Countess Kinsky von Chinic und Tettau','female','Peace',1905);
INSERT INTO "nobels" VALUES ('Charles Hard Townes','male','Physics',1964);
INSERT INTO "nobels" VALUES ('Aleksandr Mikhailovich Prokhorov','male','Physics',1964);
INSERT INTO "nobels" VALUES ('Nicolay Gennadiyevich Basov','male','Physics',1964);
INSERT INTO "nobels" VALUES ('Aage Niels Bohr','male','Physics',1975);
INSERT INTO "nobels" VALUES ('Ben Roy Mottelson','male','Physics',1975);
INSERT INTO "nobels" VALUES ('Leo James Rainwater','male','Physics',1975);
INSERT INTO "nobels" VALUES ('Artturi Ilmari Virtanen','male','Chemistry',1945);
INSERT INTO "nobels" VALUES ('Mohamed Anwar al-Sadat','male','Peace',1978);
INSERT INTO "nobels" VALUES ('Menachem Begin','male','Peace',1978);
INSERT INTO "nobels" VALUES ('Baruj Benacerraf','male','Physiology_or_Medicine',1980);
INSERT INTO "nobels" VALUES ('George D. Snell','male','Physiology_or_Medicine',1980);
INSERT INTO "nobels" VALUES ('Jean Dausset','male','Physiology_or_Medicine',1980);
INSERT INTO "nobels" VALUES ('Carl von Ossietzky','male','Peace',1935);
INSERT INTO "nobels" VALUES ('Archibald Vivian Hill','male','Physiology_or_Medicine',1922);
INSERT INTO "nobels" VALUES ('Otto Fritz Meyerhof','male','Physiology_or_Medicine',1922);
INSERT INTO "nobels" VALUES ('Carl E. Wieman','male','Physics',2001);
INSERT INTO "nobels" VALUES ('Eric A. Cornell','male','Physics',2001);
INSERT INTO "nobels" VALUES ('Wolfgang Ketterle','male','Physics',2001);
INSERT INTO "nobels" VALUES ('Andrew V. Schally','male','Physiology_or_Medicine',1977);
INSERT INTO "nobels" VALUES ('Rosalyn Yalow','female','Physiology_or_Medicine',1977);
INSERT INTO "nobels" VALUES ('Roger Guillemin','male','Physiology_or_Medicine',1977);
INSERT INTO "nobels" VALUES ('Barry J. Marshall','male','Physiology_or_Medicine',2005);
INSERT INTO "nobels" VALUES ('J. Robin Warren','male','Physiology_or_Medicine',2005);
INSERT INTO "nobels" VALUES ('Albert Fert','male','Physics',2007);
INSERT INTO "nobels" VALUES ('Peter Grünberg','male','Physics',2007);
INSERT INTO "nobels" VALUES ('Claude Simon','male','Literature',1985);
INSERT INTO "nobels" VALUES ('Alfred Hermann Fried','male','Peace',1911);
INSERT INTO "nobels" VALUES ('Tobias Michael Carel Asser','male','Peace',1911);
INSERT INTO "nobels" VALUES ('Barry C. Barish','male','Physics',2017);
INSERT INTO "nobels" VALUES ('Rainer Weiss','male','Physics',2017);
INSERT INTO "nobels" VALUES ('Kip S. Thorne','male','Physics',2017);
INSERT INTO "nobels" VALUES ('Barbara McClintock','female','Physiology_or_Medicine',1983);
INSERT INTO "nobels" VALUES ('Camillo Golgi','male','Physiology_or_Medicine',1906);
INSERT INTO "nobels" VALUES ('Santiago Ramón y Cajal','male','Physiology_or_Medicine',1906);
INSERT INTO "nobels" VALUES ('Andrei Dmitrievich Sakharov','male','Peace',1975);
INSERT INTO "nobels" VALUES ('André Lwoff','male','Physiology_or_Medicine',1965);
INSERT INTO "nobels" VALUES ('Jacques Monod','male','Physiology_or_Medicine',1965);
INSERT INTO "nobels" VALUES ('François Jacob','male','Physiology_or_Medicine',1965);
INSERT INTO "nobels" VALUES ('Alfred Werner','male','Chemistry',1913);
INSERT INTO "nobels" VALUES ('Christian de Duve','male','Physiology_or_Medicine',1974);
INSERT INTO "nobels" VALUES ('Albert Claude','male','Physiology_or_Medicine',1974);
INSERT INTO "nobels" VALUES ('George E. Palade','male','Physiology_or_Medicine',1974);
INSERT INTO "nobels" VALUES ('Andrew Fielding Huxley','male','Physiology_or_Medicine',1963);
INSERT INTO "nobels" VALUES ('Alan Lloyd Hodgkin','male','Physiology_or_Medicine',1963);
INSERT INTO "nobels" VALUES ('Sir John Carew Eccles','male','Physiology_or_Medicine',1963);
INSERT INTO "nobels" VALUES ('Arthur Henderson','male','Peace',1934);
INSERT INTO "nobels" VALUES ('Aaron Klug','male','Chemistry',1982);
INSERT INTO "nobels" VALUES ('Christopher A. Pissarides','male','Economic_Sciences',2010);
INSERT INTO "nobels" VALUES ('Peter A. Diamond','male','Economic_Sciences',2010);
INSERT INTO "nobels" VALUES ('Dale T. Mortensen','male','Economic_Sciences',2010);
INSERT INTO "nobels" VALUES ('Adolf Otto Reinhold Windaus','male','Chemistry',1928);
INSERT INTO "nobels" VALUES ('Allvar Gullstrand','male','Physiology_or_Medicine',1911);
INSERT INTO "nobels" VALUES ('Antony Hewish','male','Physics',1974);
INSERT INTO "nobels" VALUES ('Sir Martin Ryle','male','Physics',1974);
INSERT INTO "nobels" VALUES ('Ahmed H. Zewail','male','Chemistry',1999);
INSERT INTO "nobels" VALUES ('Alfred D. Hershey','male','Physiology_or_Medicine',1969);
INSERT INTO "nobels" VALUES ('Max Delbrück','male','Physiology_or_Medicine',1969);
INSERT INTO "nobels" VALUES ('Salvador E. Luria','male','Physiology_or_Medicine',1969);
INSERT INTO "nobels" VALUES ('Alfonso García Robles','male','Peace',1982);
INSERT INTO "nobels" VALUES ('Alva Myrdal','female','Peace',1982);
INSERT INTO "nobels" VALUES ('Carlo Rubbia','male','Physics',1984);
INSERT INTO "nobels" VALUES ('Simon van der Meer','male','Physics',1984);
INSERT INTO "nobels" VALUES ('Carlos Filipe Ximenes Belo','male','Peace',1996);
INSERT INTO "nobels" VALUES ('José Ramos-Horta','male','Peace',1996);
INSERT INTO "nobels" VALUES ('Albert Camus','male','Literature',1957);
INSERT INTO "nobels" VALUES ('Bob Dylan','male','Literature',2016);
INSERT INTO "nobels" VALUES ('Brian David Josephson','male','Physics',1973);
INSERT INTO "nobels" VALUES ('Leo Esaki','male','Physics',1973);
INSERT INTO "nobels" VALUES ('Ivar Giaever','male','Physics',1973);
INSERT INTO "nobels" VALUES ('Charles J. Pedersen','male','Chemistry',1987);
INSERT INTO "nobels" VALUES ('Jean-Marie Lehn','male','Chemistry',1987);
INSERT INTO "nobels" VALUES ('Donald J. Cram','male','Chemistry',1987);
INSERT INTO "nobels" VALUES ('Aaron Ciechanover','male','Chemistry',2004);
INSERT INTO "nobels" VALUES ('Avram Hershko','male','Chemistry',2004);
INSERT INTO "nobels" VALUES ('Irwin Rose','male','Chemistry',2004);
INSERT INTO "nobels" VALUES ('Carol W. Greider','female','Physiology_or_Medicine',2009);
INSERT INTO "nobels" VALUES ('Elizabeth H. Blackburn','female','Physiology_or_Medicine',2009);
INSERT INTO "nobels" VALUES ('Jack W. Szostak','male','Physiology_or_Medicine',2009);
INSERT INTO "nobels" VALUES ('Ada E. Yonath','female','Chemistry',2009);
INSERT INTO "nobels" VALUES ('Venkatraman Ramakrishnan','male','Chemistry',2009);
INSERT INTO "nobels" VALUES ('Thomas A. Steitz','male','Chemistry',2009);
INSERT INTO "nobels" VALUES ('César Milstein','male','Physiology_or_Medicine',1984);
INSERT INTO "nobels" VALUES ('Georges J.F. Köhler','male','Physiology_or_Medicine',1984);
INSERT INTO "nobels" VALUES ('Niels K. Jerne','male','Physiology_or_Medicine',1984);
INSERT INTO "nobels" VALUES ('Charles Louis Alphonse Laveran','male','Physiology_or_Medicine',1907);
INSERT INTO "nobels" VALUES ('Arthur Kornberg','male','Physiology_or_Medicine',1959);
INSERT INTO "nobels" VALUES ('Severo Ochoa','male','Physiology_or_Medicine',1959);
INSERT INTO "nobels" VALUES ('Cecil Frank Powell','male','Physics',1950);
INSERT INTO "nobels" VALUES ('Christiane Nüsslein-Volhard','female','Physiology_or_Medicine',1995);
INSERT INTO "nobels" VALUES ('Edward B. Lewis','male','Physiology_or_Medicine',1995);
INSERT INTO "nobels" VALUES ('Eric F. Wieschaus','male','Physiology_or_Medicine',1995);
INSERT INTO "nobels" VALUES ('Bruce A. Beutler','male','Physiology_or_Medicine',2011);
INSERT INTO "nobels" VALUES ('Jules A. Hoffmann','male','Physiology_or_Medicine',2011);
INSERT INTO "nobels" VALUES ('Ralph M. Steinman','male','Physiology_or_Medicine',2011);
INSERT INTO "nobels" VALUES ('Abiy Ahmed Ali','male','Peace',2019);
INSERT INTO "nobels" VALUES ('Schack August Steenberg Krogh','male','Physiology_or_Medicine',1920);
INSERT INTO "nobels" VALUES ('Arvid Carlsson','male','Physiology_or_Medicine',2000);
INSERT INTO "nobels" VALUES ('Eric R. Kandel','male','Physiology_or_Medicine',2000);
INSERT INTO "nobels" VALUES ('Paul Greengard','male','Physiology_or_Medicine',2000);
INSERT INTO "nobels" VALUES ('André Frédéric Cournand','male','Physiology_or_Medicine',1956);
INSERT INTO "nobels" VALUES ('Dickinson W. Richards','male','Physiology_or_Medicine',1956);
INSERT INTO "nobels" VALUES ('Werner Forssmann','male','Physiology_or_Medicine',1956);
INSERT INTO "nobels" VALUES ('Alan G. MacDiarmid','male','Chemistry',2000);
INSERT INTO "nobels" VALUES ('Alan J. Heeger','male','Chemistry',2000);
INSERT INTO "nobels" VALUES ('Hideki Shirakawa','male','Chemistry',2000);
INSERT INTO "nobels" VALUES ('Brian K. Kobilka','male','Chemistry',2012);
INSERT INTO "nobels" VALUES ('Robert J. Lefkowitz','male','Chemistry',2012);
INSERT INTO "nobels" VALUES ('Charles M. Rice','male','Physiology_or_Medicine',2020);
INSERT INTO "nobels" VALUES ('Michael Houghton','male','Physiology_or_Medicine',2020);
INSERT INTO "nobels" VALUES ('Harvey J. Alter','male','Physiology_or_Medicine',2020);
INSERT INTO "nobels" VALUES ('Robert Bruce Merrifield','male','Chemistry',1984);
INSERT INTO "nobels" VALUES ('Akira Suzuki','male','Chemistry',2010);
INSERT INTO "nobels" VALUES ('Ei-ichi Negishi','male','Chemistry',2010);
INSERT INTO "nobels" VALUES ('Richard F. Heck','male','Chemistry',2010);
INSERT INTO "nobels" VALUES ('Christopher A. Sims','male','Economic_Sciences',2011);
INSERT INTO "nobels" VALUES ('Thomas J. Sargent','male','Economic_Sciences',2011);
INSERT INTO "nobels" VALUES ('Bengt Holmström','male','Economic_Sciences',2016);
INSERT INTO "nobels" VALUES ('Oliver Hart','male','Economic_Sciences',2016);
INSERT INTO "nobels" VALUES ('Adolf Friedrich Johann Butenandt','male','Chemistry',1939);
INSERT INTO "nobels" VALUES ('Leopold Ruzicka','male','Chemistry',1939);
INSERT INTO "nobels" VALUES ('Abdus Salam','male','Physics',1979);
INSERT INTO "nobels" VALUES ('Sheldon Lee Glashow','male','Physics',1979);
INSERT INTO "nobels" VALUES ('Steven Weinberg','male','Physics',1979);
INSERT INTO "nobels" VALUES ('Albrecht Kossel','male','Physiology_or_Medicine',1910);
INSERT INTO "nobels" VALUES ('Antoine Henri Becquerel','male','Physics',1903);
INSERT INTO "nobels" VALUES ('Marie Curie, née Sklodowska','female','Physics',1903);
INSERT INTO "nobels" VALUES ('Pierre Curie','male','Physics',1903);
INSERT INTO "nobels" VALUES ('Baruch S. Blumberg','male','Physiology_or_Medicine',1976);
INSERT INTO "nobels" VALUES ('D. Carleton Gajdusek','male','Physiology_or_Medicine',1976);
INSERT INTO "nobels" VALUES ('Carl Friedrich Georg Spitteler','male','Literature',1919);
INSERT INTO "nobels" VALUES ('Bernard L. Feringa','male','Chemistry',2016);
INSERT INTO "nobels" VALUES ('Sir J. Fraser Stoddart','male','Chemistry',2016);
INSERT INTO "nobels" VALUES ('Jean-Pierre Sauvage','male','Chemistry',2016);
INSERT INTO "nobels" VALUES ('Camilo José Cela','male','Literature',1989);
INSERT INTO "nobels" VALUES ('Christian Lous Lange','male','Peace',1921);
INSERT INTO "nobels" VALUES ('Karl Hjalmar Branting','male','Peace',1921);
INSERT INTO "nobels" VALUES ('Claude Cohen-Tannoudji','male','Physics',1997);
INSERT INTO "nobels" VALUES ('Steven Chu','male','Physics',1997);
INSERT INTO "nobels" VALUES ('William D. Phillips','male','Physics',1997);
INSERT INTO "nobels" VALUES ('Akira Yoshino','male','Chemistry',2019);
INSERT INTO "nobels" VALUES ('John B. Goodenough','male','Chemistry',2019);
INSERT INTO "nobels" VALUES ('M. Stanley Whittingham','male','Chemistry',2019);
INSERT INTO "nobels" VALUES ('Bjørnstjerne Martinus Bjørnson','male','Literature',1903);
INSERT INTO "nobels" VALUES ('Carlos Saavedra Lamas','male','Peace',1936);
INSERT INTO "nobels" VALUES ('Boris Leonidovich Pasternak','male','Literature',1958);
INSERT INTO "nobels" VALUES ('Andrew Z. Fire','male','Physiology_or_Medicine',2006);
INSERT INTO "nobels" VALUES ('Craig C. Mello','male','Physiology_or_Medicine',2006);
INSERT INTO "nobels" VALUES ('K. Barry Sharpless','male','Chemistry',2001);
INSERT INTO "nobels" VALUES ('Ryoji Noyori','male','Chemistry',2001);
INSERT INTO "nobels" VALUES ('William S. Knowles','male','Chemistry',2001);
INSERT INTO "nobels" VALUES ('Johann Friedrich Wilhelm Adolf von Baeyer','male','Chemistry',1905);
INSERT INTO "nobels" VALUES ('Carl David Anderson','male','Physics',1936);
INSERT INTO "nobels" VALUES ('Victor Franz Hess','male','Physics',1936);
INSERT INTO "nobels" VALUES ('Allan M. Cormack','male','Physiology_or_Medicine',1979);
INSERT INTO "nobels" VALUES ('Godfrey N. Hounsfield','male','Physiology_or_Medicine',1979);
INSERT INTO "nobels" VALUES ('Charles Gates Dawes','male','Peace',1925);
INSERT INTO "nobels" VALUES ('Sir Austen Chamberlain','male','Peace',1925);
INSERT INTO "nobels" VALUES ('Aziz Sancar','male','Chemistry',2015);
INSERT INTO "nobels" VALUES ('Tomas Lindahl','male','Chemistry',2015);
INSERT INTO "nobels" VALUES ('Paul Modrich','male','Chemistry',2015);
INSERT INTO "nobels" VALUES ('Wilhelm Conrad Röntgen','male','Physics',1901);
INSERT INTO "nobels" VALUES ('Alice Munro','female','Literature',2013);
INSERT INTO "nobels" VALUES ('Arthur B. McDonald','male','Physics',2015);
INSERT INTO "nobels" VALUES ('Takaaki Kajita','male','Physics',2015);
INSERT INTO "nobels" VALUES ('Arthur Leonard Schawlow','male','Physics',1981);
INSERT INTO "nobels" VALUES ('Kai M. Siegbahn','male','Physics',1981);
INSERT INTO "nobels" VALUES ('Nicolaas Bloembergen','male','Physics',1981);
INSERT INTO "nobels" VALUES ('Charles Kuen Kao','male','Physics',2009);
INSERT INTO "nobels" VALUES ('Willard S. Boyle','male','Physics',2009);
INSERT INTO "nobels" VALUES ('George E. Smith','male','Physics',2009);
INSERT INTO "nobels" VALUES ('Bengt I. Samuelsson','male','Physiology_or_Medicine',1982);
INSERT INTO "nobels" VALUES ('John R. Vane','male','Physiology_or_Medicine',1982);
INSERT INTO "nobels" VALUES ('Sune K. Bergström','male','Physiology_or_Medicine',1982);
INSERT INTO "nobels" VALUES ('Chen Ning Yang','male','Physics',1957);
INSERT INTO "nobels" VALUES ('Tsung-Dao (T.D.) Lee','male','Physics',1957);
INSERT INTO "nobels" VALUES ('Aleksandr Isayevich Solzhenitsyn','male','Literature',1970);
INSERT INTO "nobels" VALUES ('Christiaan Eijkman','male','Physiology_or_Medicine',1929);
INSERT INTO "nobels" VALUES ('Sir Frederick Gowland Hopkins','male','Physiology_or_Medicine',1929);
INSERT INTO "nobels" VALUES ('Carl Bosch','male','Chemistry',1931);
INSERT INTO "nobels" VALUES ('Friedrich Bergius','male','Chemistry',1931);
INSERT INTO "nobels" VALUES ('Albert John Lutuli','male','Peace',1960);
INSERT INTO "nobels" VALUES ('Albert von Szent-Györgyi Nagyrápolt','male','Physiology_or_Medicine',1937);
INSERT INTO "nobels" VALUES ('Anatole France','male','Literature',1921);
INSERT INTO "nobels" VALUES ('Alfred Kastler','male','Physics',1966);
INSERT INTO "nobels" VALUES ('Arieh Warshel','male','Chemistry',2013);
INSERT INTO "nobels" VALUES ('Michael Levitt','male','Chemistry',2013);
INSERT INTO "nobels" VALUES ('Martin Karplus','male','Chemistry',2013);
INSERT INTO "nobels" VALUES ('Arthur Harden','male','Chemistry',1929);
INSERT INTO "nobels" VALUES ('Hans Karl August Simon von Euler-Chelpin','male','Chemistry',1929);
INSERT INTO "nobels" VALUES ('Bert Sakmann','male','Physiology_or_Medicine',1991);
INSERT INTO "nobels" VALUES ('Erwin Neher','male','Physiology_or_Medicine',1991);
INSERT INTO "nobels" VALUES ('Charles Jules Henri Nicolle','male','Physiology_or_Medicine',1928);
INSERT INTO "nobels" VALUES ('Aristide Briand','male','Peace',1926);
INSERT INTO "nobels" VALUES ('Gustav Stresemann','male','Peace',1926);
INSERT INTO "nobels" VALUES ('Elizabeth Williams','female','Peace',1976);
INSERT INTO "nobels" VALUES ('Mairead Corrigan','female','Peace',1976);
INSERT INTO "nobels" VALUES ('Charles Glover Barkla','male','Physics',1917);
INSERT INTO "nobels" VALUES ('Arne Wilhelm Kaurin Tiselius','male','Chemistry',1948);
INSERT INTO "nobels" VALUES ('Albert Abraham Michelson','male','Physics',1907);
INSERT INTO "nobels" VALUES ('Abhijit Banerjee','male','Economic_Sciences',2019);
INSERT INTO "nobels" VALUES ('Esther Duflo','female','Economic_Sciences',2019);
INSERT INTO "nobels" VALUES ('Michael Kremer','male','Economic_Sciences',2019);
INSERT INTO "nobels" VALUES ('Charles Edouard Guillaume','male','Physics',1920);
INSERT INTO "nobels" VALUES ('Albert Einstein','male','Physics',1921);
INSERT INTO "nobels" VALUES ('Auguste Marie François Beernaert','male','Peace',1909);
INSERT INTO "nobels" VALUES ('Paul Henri Benjamin Balluet d''Estournelles de Constant, Baron de Constant de Rebecque','male','Peace',1909);
INSERT INTO "nobels" VALUES ('Alvin E. Roth','male','Economic_Sciences',2012);
INSERT INTO "nobels" VALUES ('Lloyd S. Shapley','male','Economic_Sciences',2012);
INSERT INTO "nobels" VALUES ('Theodore Roosevelt Jr.','male','Peace',1906);
INSERT INTO "nobels" VALUES ('Luis Walter Alvarez','male','Physics',1968);
INSERT INTO "nobels" VALUES ('Derek H. R. Barton','male','Chemistry',1969);
INSERT INTO "nobels" VALUES ('Odd Hassel','male','Chemistry',1969);
INSERT INTO "nobels" VALUES ('George A. Olah','male','Chemistry',1994);
INSERT INTO "nobels" VALUES ('Rudolf Ludwig Mössbauer','male','Physics',1961);
INSERT INTO "nobels" VALUES ('Robert Hofstadter','male','Physics',1961);
INSERT INTO "nobels" VALUES ('Dag Hjalmar Agne Carl Hammarskjöld','male','Peace',1961);
INSERT INTO "nobels" VALUES ('Oliver Smithies','male','Physiology_or_Medicine',2007);
INSERT INTO "nobels" VALUES ('Mario R. Capecchi','male','Physiology_or_Medicine',2007);
INSERT INTO "nobels" VALUES ('Sir Martin J. Evans','male','Physiology_or_Medicine',2007);
INSERT INTO "nobels" VALUES ('Robert J. Aumann','male','Economic_Sciences',2005);
INSERT INTO "nobels" VALUES ('Thomas C. Schelling','male','Economic_Sciences',2005);
INSERT INTO "nobels" VALUES ('Sir Edward Victor Appleton','male','Physics',1947);
INSERT INTO "nobels" VALUES ('William C. Campbell','male','Physiology_or_Medicine',2015);
INSERT INTO "nobels" VALUES ('Satoshi Ōmura','male','Physiology_or_Medicine',2015);
INSERT INTO "nobels" VALUES ('Tu Youyou','female','Physiology_or_Medicine',2015);
INSERT INTO "nobels" VALUES ('Elfriede Jelinek','female','Literature',2004);
INSERT INTO "nobels" VALUES ('Murray Gell-Mann','male','Physics',1969);
INSERT INTO "nobels" VALUES ('John Galsworthy','male','Literature',1932);
INSERT INTO "nobels" VALUES ('Elias Canetti','male','Literature',1981);
INSERT INTO "nobels" VALUES ('Wilhelm Wien','male','Physics',1911);
INSERT INTO "nobels" VALUES ('Clive W.J. Granger','male','Economic_Sciences',2003);
INSERT INTO "nobels" VALUES ('Robert F. Engle III','male','Economic_Sciences',2003);
INSERT INTO "nobels" VALUES ('Rita Levi-Montalcini','female','Physiology_or_Medicine',1986);
INSERT INTO "nobels" VALUES ('Stanley Cohen','male','Physiology_or_Medicine',1986);
INSERT INTO "nobels" VALUES ('Richard Kuhn','male','Chemistry',1938);
INSERT INTO "nobels" VALUES ('Eugene F. Fama','male','Economic_Sciences',2013);
INSERT INTO "nobels" VALUES ('Lars Peter Hansen','male','Economic_Sciences',2013);
INSERT INTO "nobels" VALUES ('Robert J. Shiller','male','Economic_Sciences',2013);
INSERT INTO "nobels" VALUES ('Kazuo Ishiguro','male','Literature',2017);
INSERT INTO "nobels" VALUES ('Doris Lessing','female','Literature',2007);
INSERT INTO "nobels" VALUES ('Jack S. Kilby','male','Physics',2000);
INSERT INTO "nobels" VALUES ('Zhores I. Alferov','male','Physics',2000);
INSERT INTO "nobels" VALUES ('Herbert Kroemer','male','Physics',2000);
INSERT INTO "nobels" VALUES ('Thomas Mann','male','Literature',1929);
INSERT INTO "nobels" VALUES ('Joseph Rotblat','male','Peace',1995);
INSERT INTO "nobels" VALUES ('Sir Nevill Francis Mott','male','Physics',1977);
INSERT INTO "nobels" VALUES ('John Hasbrouck Van Vleck','male','Physics',1977);
INSERT INTO "nobels" VALUES ('Philip Warren Anderson','male','Physics',1977);
INSERT INTO "nobels" VALUES ('Henri La Fontaine','male','Peace',1913);
INSERT INTO "nobels" VALUES ('Elie Wiesel','male','Peace',1986);
INSERT INTO "nobels" VALUES ('Paul Karrer','male','Chemistry',1937);
INSERT INTO "nobels" VALUES ('Walter Norman Haworth','male','Chemistry',1937);
INSERT INTO "nobels" VALUES ('Shirin Ebadi','female','Peace',2003);
INSERT INTO "nobels" VALUES ('Tim Hunt','male','Physiology_or_Medicine',2001);
INSERT INTO "nobels" VALUES ('Sir Paul M. Nurse','male','Physiology_or_Medicine',2001);
INSERT INTO "nobels" VALUES ('Leland H. Hartwell','male','Physiology_or_Medicine',2001);
INSERT INTO "nobels" VALUES ('Johannes Diderik van der Waals','male','Physics',1910);
INSERT INTO "nobels" VALUES ('Count Maurice (Mooris) Polidore Marie Bernhard Maeterlinck','male','Literature',1911);
INSERT INTO "nobels" VALUES ('Feodor Lynen','male','Physiology_or_Medicine',1964);
INSERT INTO "nobels" VALUES ('Konrad Bloch','male','Physiology_or_Medicine',1964);
INSERT INTO "nobels" VALUES ('Petrus (Peter) Josephus Wilhelmus Debye','male','Chemistry',1936);
INSERT INTO "nobels" VALUES ('Pieter Zeeman','male','Physics',1902);
INSERT INTO "nobels" VALUES ('Hendrik Antoon Lorentz','male','Physics',1902);
INSERT INTO "nobels" VALUES ('Rudyard Kipling','male','Literature',1907);
INSERT INTO "nobels" VALUES ('Sully Prudhomme','male','Literature',1901);
INSERT INTO "nobels" VALUES ('Val Logsdon Fitch','male','Physics',1980);
INSERT INTO "nobels" VALUES ('James Watson Cronin','male','Physics',1980);
INSERT INTO "nobels" VALUES ('Karl Ziegler','male','Chemistry',1963);
INSERT INTO "nobels" VALUES ('Giulio Natta','male','Chemistry',1963);
INSERT INTO "nobels" VALUES ('Yasser Arafat','male','Peace',1994);
INSERT INTO "nobels" VALUES ('Yitzhak Rabin','male','Peace',1994);
INSERT INTO "nobels" VALUES ('Shimon Peres','male','Peace',1994);
INSERT INTO "nobels" VALUES ('Roger B. Myerson','male','Economic_Sciences',2007);
INSERT INTO "nobels" VALUES ('Eric S. Maskin','male','Economic_Sciences',2007);
INSERT INTO "nobels" VALUES ('Leonid Hurwicz','male','Economic_Sciences',2007);
INSERT INTO "nobels" VALUES ('Martin Luther King Jr.','male','Peace',1964);
INSERT INTO "nobels" VALUES ('Denis Mukwege','male','Peace',2018);
INSERT INTO "nobels" VALUES ('Nadia Murad Basee Taha','female','Peace',2018);
INSERT INTO "nobels" VALUES ('Sir William Henry Bragg','male','Physics',1915);
INSERT INTO "nobels" VALUES ('William Lawrence Bragg','male','Physics',1915);
INSERT INTO "nobels" VALUES ('Christian Matthias Theodor Mommsen','male','Literature',1902);
INSERT INTO "nobels" VALUES ('Walter Rudolf Hess','male','Physiology_or_Medicine',1949);
INSERT INTO "nobels" VALUES ('António Caetano de Abreu Freire Egas Moniz','male','Physiology_or_Medicine',1949);
INSERT INTO "nobels" VALUES ('John R. Hicks','male','Economic_Sciences',1972);
INSERT INTO "nobels" VALUES ('Kenneth J. Arrow','male','Economic_Sciences',1972);
INSERT INTO "nobels" VALUES ('Jean Henry Dunant','male','Peace',1901);
INSERT INTO "nobels" VALUES ('Frédéric Passy','male','Peace',1901);
INSERT INTO "nobels" VALUES ('Richard Henderson','male','Chemistry',2017);
INSERT INTO "nobels" VALUES ('Joachim Frank','male','Chemistry',2017);
INSERT INTO "nobels" VALUES ('Jacques Dubochet','male','Chemistry',2017);
INSERT INTO "nobels" VALUES ('Elinor Ostrom','female','Economic_Sciences',2009);
INSERT INTO "nobels" VALUES ('Oliver E. Williamson','male','Economic_Sciences',2009);
INSERT INTO "nobels" VALUES ('Dorothy Crowfoot Hodgkin','female','Chemistry',1964);
INSERT INTO "nobels" VALUES ('Robert B. Wilson','male','Economic_Sciences',2020);
INSERT INTO "nobels" VALUES ('Paul R. Milgrom','male','Economic_Sciences',2020);
INSERT INTO "nobels" VALUES ('Paul D. Boyer','male','Chemistry',1997);
INSERT INTO "nobels" VALUES ('Jens C. Skou','male','Chemistry',1997);
INSERT INTO "nobels" VALUES ('John E. Walker','male','Chemistry',1997);
INSERT INTO "nobels" VALUES ('Henryk Sienkiewicz','male','Literature',1905);
INSERT INTO "nobels" VALUES ('Walther Bothe','male','Physics',1954);
INSERT INTO "nobels" VALUES ('Max Born','male','Physics',1954);
INSERT INTO "nobels" VALUES ('Masatoshi Koshiba','male','Physics',2002);
INSERT INTO "nobels" VALUES ('Raymond Davis Jr.','male','Physics',2002);
INSERT INTO "nobels" VALUES ('Riccardo Giacconi','male','Physics',2002);
INSERT INTO "nobels" VALUES ('Svetlana Alexievich','female','Literature',2015);
INSERT INTO "nobels" VALUES ('Frances H. Arnold','female','Chemistry',2018);
INSERT INTO "nobels" VALUES ('Sir Gregory P. Winter','male','Chemistry',2018);
INSERT INTO "nobels" VALUES ('George P. Smith','male','Chemistry',2018);
INSERT INTO "nobels" VALUES ('Ivan Alekseyevich Bunin','male','Literature',1933);
INSERT INTO "nobels" VALUES ('Gabriela Mistral','female','Literature',1945);
INSERT INTO "nobels" VALUES ('William Parry Murphy','male','Physiology_or_Medicine',1934);
INSERT INTO "nobels" VALUES ('George Richards Minot','male','Physiology_or_Medicine',1934);
INSERT INTO "nobels" VALUES ('George Hoyt Whipple','male','Physiology_or_Medicine',1934);
INSERT INTO "nobels" VALUES ('Mario Vargas Llosa','male','Literature',2010);
INSERT INTO "nobels" VALUES ('Ulf von Euler','male','Physiology_or_Medicine',1970);
INSERT INTO "nobels" VALUES ('Sir Bernard Katz','male','Physiology_or_Medicine',1970);
INSERT INTO "nobels" VALUES ('Julius Axelrod','male','Physiology_or_Medicine',1970);
INSERT INTO "nobels" VALUES ('Harold Pinter','male','Literature',2005);
INSERT INTO "nobels" VALUES ('Willis Eugene Lamb','male','Physics',1955);
INSERT INTO "nobels" VALUES ('Polykarp Kusch','male','Physics',1955);
INSERT INTO "nobels" VALUES ('The (Theodor) Svedberg','male','Chemistry',1926);
INSERT INTO "nobels" VALUES ('Seán MacBride','male','Peace',1974);
INSERT INTO "nobels" VALUES ('Eisaku Sato','male','Peace',1974);
INSERT INTO "nobels" VALUES ('Gary S. Becker','male','Economic_Sciences',1992);
INSERT INTO "nobels" VALUES ('Niels Ryberg Finsen','male','Physiology_or_Medicine',1903);
INSERT INTO "nobels" VALUES ('Robert G. Edwards','male','Physiology_or_Medicine',2010);
INSERT INTO "nobels" VALUES ('Edvard I. Moser','male','Physiology_or_Medicine',2014);
INSERT INTO "nobels" VALUES ('John O''Keefe','male','Physiology_or_Medicine',2014);
INSERT INTO "nobels" VALUES ('May-Britt Moser','female','Physiology_or_Medicine',2014);
INSERT INTO "nobels" VALUES ('George J. Stigler','male','Economic_Sciences',1982);
INSERT INTO "nobels" VALUES ('Otto Heinrich Warburg','male','Physiology_or_Medicine',1931);
INSERT INTO "nobels" VALUES ('Wilhelm Ostwald','male','Chemistry',1909);
INSERT INTO "nobels" VALUES ('Kenichi Fukui','male','Chemistry',1981);
INSERT INTO "nobels" VALUES ('Roald Hoffmann','male','Chemistry',1981);
INSERT INTO "nobels" VALUES ('François Mauriac','male','Literature',1952);
INSERT INTO "nobels" VALUES ('Nikolay Nikolaevich Semenov','male','Chemistry',1956);
INSERT INTO "nobels" VALUES ('Sir Cyril Norman Hinshelwood','male','Chemistry',1956);
INSERT INTO "nobels" VALUES ('Jane Addams','female','Peace',1931);
INSERT INTO "nobels" VALUES ('Nicholas Murray Butler','male','Peace',1931);
INSERT INTO "nobels" VALUES ('Peter Agre','male','Chemistry',2003);
INSERT INTO "nobels" VALUES ('Roderick MacKinnon','male','Chemistry',2003);
INSERT INTO "nobels" VALUES ('Sir Arthur Lewis','male','Economic_Sciences',1979);
INSERT INTO "nobels" VALUES ('Theodore W. Schultz','male','Economic_Sciences',1979);
INSERT INTO "nobels" VALUES ('Karl Landsteiner','male','Physiology_or_Medicine',1930);
INSERT INTO "nobels" VALUES ('Makoto Kobayashi','male','Physics',2008);
INSERT INTO "nobels" VALUES ('Yoichiro Nambu','male','Physics',2008);
INSERT INTO "nobels" VALUES ('Toshihide Maskawa','male','Physics',2008);
INSERT INTO "nobels" VALUES ('Michael Smith','male','Chemistry',1993);
INSERT INTO "nobels" VALUES ('Kary B. Mullis','male','Chemistry',1993);
INSERT INTO "nobels" VALUES ('Thomas Hunt Morgan','male','Physiology_or_Medicine',1933);
INSERT INTO "nobels" VALUES ('William Francis Giauque','male','Chemistry',1949);
INSERT INTO "nobels" VALUES ('Grazia Deledda','female','Literature',1926);
INSERT INTO "nobels" VALUES ('Gerd Binnig','male','Physics',1986);
INSERT INTO "nobels" VALUES ('Heinrich Rohrer','male','Physics',1986);
INSERT INTO "nobels" VALUES ('Ernst Ruska','male','Physics',1986);
INSERT INTO "nobels" VALUES ('William Randal Cremer','male','Peace',1903);
INSERT INTO "nobels" VALUES ('Paul Hermann Müller','male','Physiology_or_Medicine',1948);
INSERT INTO "nobels" VALUES ('Derek Walcott','male','Literature',1992);
INSERT INTO "nobels" VALUES ('Knut Pedersen Hamsun','male','Literature',1920);
INSERT INTO "nobels" VALUES ('Eduard Buchner','male','Chemistry',1907);
INSERT INTO "nobels" VALUES ('Georges Pire','male','Peace',1958);
INSERT INTO "nobels" VALUES ('Ferdinand Buisson','male','Peace',1927);
INSERT INTO "nobels" VALUES ('Ludwig Quidde','male','Peace',1927);
INSERT INTO "nobels" VALUES ('Robert W. Holley','male','Physiology_or_Medicine',1968);
INSERT INTO "nobels" VALUES ('Har Gobind Khorana','male','Physiology_or_Medicine',1968);
INSERT INTO "nobels" VALUES ('Marshall W. Nirenberg','male','Physiology_or_Medicine',1968);
INSERT INTO "nobels" VALUES ('Shinya Yamanaka','male','Physiology_or_Medicine',2012);
INSERT INTO "nobels" VALUES ('Sir John B. Gurdon','male','Physiology_or_Medicine',2012);
INSERT INTO "nobels" VALUES ('Ellen Johnson Sirleaf','female','Peace',2011);
INSERT INTO "nobels" VALUES ('Leymah Gbowee','female','Peace',2011);
INSERT INTO "nobels" VALUES ('Tawakkol Karman','female','Peace',2011);
INSERT INTO "nobels" VALUES ('Isidor Isaac Rabi','male','Physics',1944);
INSERT INTO "nobels" VALUES ('Richard Adolf Zsigmondy','male','Chemistry',1925);
INSERT INTO "nobels" VALUES ('Hermann Emil Fischer','male','Chemistry',1902);
INSERT INTO "nobels" VALUES ('Selma Ottilia Lovisa Lagerlöf','female','Literature',1909);
INSERT INTO "nobels" VALUES ('Ivo Andric','male','Literature',1961);
INSERT INTO "nobels" VALUES ('Ernest Orlando Lawrence','male','Physics',1939);
INSERT INTO "nobels" VALUES ('Klaus von Klitzing','male','Physics',1985);
INSERT INTO "nobels" VALUES ('E. Donnall Thomas','male','Physiology_or_Medicine',1990);
INSERT INTO "nobels" VALUES ('Joseph E. Murray','male','Physiology_or_Medicine',1990);
INSERT INTO "nobels" VALUES ('Salvatore Quasimodo','male','Literature',1959);
INSERT INTO "nobels" VALUES ('Kurt Wüthrich','male','Chemistry',2002);
INSERT INTO "nobels" VALUES ('John B. Fenn','male','Chemistry',2002);
INSERT INTO "nobels" VALUES ('Koichi Tanaka','male','Chemistry',2002);
INSERT INTO "nobels" VALUES ('Linda B. Buck','female','Physiology_or_Medicine',2004);
INSERT INTO "nobels" VALUES ('Richard Axel','male','Physiology_or_Medicine',2004);
INSERT INTO "nobels" VALUES ('Daniel Nathans','male','Physiology_or_Medicine',1978);
INSERT INTO "nobels" VALUES ('Hamilton O. Smith','male','Physiology_or_Medicine',1978);
INSERT INTO "nobels" VALUES ('Werner Arber','male','Physiology_or_Medicine',1978);
INSERT INTO "nobels" VALUES ('Sir James W. Black','male','Physiology_or_Medicine',1988);
INSERT INTO "nobels" VALUES ('George H. Hitchings','male','Physiology_or_Medicine',1988);
INSERT INTO "nobels" VALUES ('Gertrude B. Elion','female','Physiology_or_Medicine',1988);
INSERT INTO "nobels" VALUES ('Joseph Erlanger','male','Physiology_or_Medicine',1944);
INSERT INTO "nobels" VALUES ('Herbert Spencer Gasser','male','Physiology_or_Medicine',1944);
INSERT INTO "nobels" VALUES ('Heike Kamerlingh Onnes','male','Physics',1913);
INSERT INTO "nobels" VALUES ('René Cassin','male','Peace',1968);
INSERT INTO "nobels" VALUES ('Georges Charpak','male','Physics',1992);
INSERT INTO "nobels" VALUES ('Norman F. Ramsey','male','Physics',1989);
INSERT INTO "nobels" VALUES ('Hans G. Dehmelt','male','Physics',1989);
INSERT INTO "nobels" VALUES ('Wolfgang Paul','male','Physics',1989);
INSERT INTO "nobels" VALUES ('Otto Wallach','male','Chemistry',1910);
INSERT INTO "nobels" VALUES ('Gabriel García Márquez','male','Literature',1982);
INSERT INTO "nobels" VALUES ('Selman Abraham Waksman','male','Physiology_or_Medicine',1952);
INSERT INTO "nobels" VALUES ('Hartmut Michel','male','Chemistry',1988);
INSERT INTO "nobels" VALUES ('Johann Deisenhofer','male','Chemistry',1988);
INSERT INTO "nobels" VALUES ('Robert Huber','male','Chemistry',1988);
INSERT INTO "nobels" VALUES ('James Dewey Watson','male','Physiology_or_Medicine',1962);
INSERT INTO "nobels" VALUES ('Maurice Hugh Frederick Wilkins','male','Physiology_or_Medicine',1962);
INSERT INTO "nobels" VALUES ('Francis Harry Compton Crick','male','Physiology_or_Medicine',1962);
INSERT INTO "nobels" VALUES ('Friedrich August von Hayek','male','Economic_Sciences',1974);
INSERT INTO "nobels" VALUES ('Gunnar Myrdal','male','Economic_Sciences',1974);
INSERT INTO "nobels" VALUES ('Kenzaburo Oe','male','Literature',1994);
INSERT INTO "nobels" VALUES ('Lord (Alexander R.) Todd','male','Chemistry',1957);
INSERT INTO "nobels" VALUES ('Karl Ferdinand Braun','male','Physics',1909);
INSERT INTO "nobels" VALUES ('Guglielmo Marconi','male','Physics',1909);
INSERT INTO "nobels" VALUES ('Jody Williams','female','Peace',1997);
INSERT INTO "nobels" VALUES ('William Vickrey','male','Economic_Sciences',1996);
INSERT INTO "nobels" VALUES ('James A. Mirrlees','male','Economic_Sciences',1996);
INSERT INTO "nobels" VALUES ('F. Sherwood Rowland','male','Chemistry',1995);
INSERT INTO "nobels" VALUES ('Paul J. Crutzen','male','Chemistry',1995);
INSERT INTO "nobels" VALUES ('Mario J. Molina','male','Chemistry',1995);
INSERT INTO "nobels" VALUES ('Lev Davidovich Landau','male','Physics',1962);
INSERT INTO "nobels" VALUES ('John Bardeen','male','Physics',1956);
INSERT INTO "nobels" VALUES ('Walter Houser Brattain','male','Physics',1956);
INSERT INTO "nobels" VALUES ('William Bradford Shockley','male','Physics',1956);
INSERT INTO "nobels" VALUES ('John Bardeen','male','Physics',1972);
INSERT INTO "nobels" VALUES ('Leon Neil Cooper','male','Physics',1972);
INSERT INTO "nobels" VALUES ('John Robert Schrieffer','male','Physics',1972);
INSERT INTO "nobels" VALUES ('John James Rickard Macleod','male','Physiology_or_Medicine',1923);
INSERT INTO "nobels" VALUES ('Frederick Grant Banting','male','Physiology_or_Medicine',1923);
INSERT INTO "nobels" VALUES ('Emil Adolf von Behring','male','Physiology_or_Medicine',1901);
INSERT INTO "nobels" VALUES ('Orhan Pamuk','male','Literature',2006);
INSERT INTO "nobels" VALUES ('Ralph Bunche','male','Peace',1950);
INSERT INTO "nobels" VALUES ('Leonid Vitaliyevich Kantorovich','male','Economic_Sciences',1975);
INSERT INTO "nobels" VALUES ('Tjalling C. Koopmans','male','Economic_Sciences',1975);
INSERT INTO "nobels" VALUES ('Sir Robert Robinson','male','Chemistry',1947);
INSERT INTO "nobels" VALUES ('Frank Wilczek','male','Physics',2004);
INSERT INTO "nobels" VALUES ('David J. Gross','male','Physics',2004);
INSERT INTO "nobels" VALUES ('H. David Politzer','male','Physics',2004);
INSERT INTO "nobels" VALUES ('George Bernard Shaw','male','Literature',1925);
INSERT INTO "nobels" VALUES ('Kenneth G. Wilson','male','Physics',1982);
INSERT INTO "nobels" VALUES ('Hans Adolf Krebs','male','Physiology_or_Medicine',1953);
INSERT INTO "nobels" VALUES ('Fritz Albert Lipmann','male','Physiology_or_Medicine',1953);
INSERT INTO "nobels" VALUES ('Frank Billings Kellogg','male','Peace',1929);
INSERT INTO "nobels" VALUES ('Peter Brian Medawar','male','Physiology_or_Medicine',1960);
INSERT INTO "nobels" VALUES ('Sir Frank Macfarlane Burnet','male','Physiology_or_Medicine',1960);
INSERT INTO "nobels" VALUES ('Axel Hugo Theodor Theorell','male','Physiology_or_Medicine',1955);
INSERT INTO "nobels" VALUES ('H. Robert Horvitz','male','Physiology_or_Medicine',2002);
INSERT INTO "nobels" VALUES ('John E. Sulston','male','Physiology_or_Medicine',2002);
INSERT INTO "nobels" VALUES ('Sydney Brenner','male','Physiology_or_Medicine',2002);
INSERT INTO "nobels" VALUES ('J. Michael Bishop','male','Physiology_or_Medicine',1989);
INSERT INTO "nobels" VALUES ('Harold E. Varmus','male','Physiology_or_Medicine',1989);
INSERT INTO "nobels" VALUES ('Sir Harold W. Kroto','male','Chemistry',1996);
INSERT INTO "nobels" VALUES ('Robert F. Curl Jr.','male','Chemistry',1996);
INSERT INTO "nobels" VALUES ('Richard E. Smalley','male','Chemistry',1996);
INSERT INTO "nobels" VALUES ('Vicente Aleixandre','male','Literature',1977);
INSERT INTO "nobels" VALUES ('Paul C. Lauterbur','male','Physiology_or_Medicine',2003);
INSERT INTO "nobels" VALUES ('Sir Peter Mansfield','male','Physiology_or_Medicine',2003);
INSERT INTO "nobels" VALUES ('Harold Clayton Urey','male','Chemistry',1934);
INSERT INTO "nobels" VALUES ('Heinrich Böll','male','Literature',1972);
INSERT INTO "nobels" VALUES ('Frederick Sanger','male','Chemistry',1958);
INSERT INTO "nobels" VALUES ('Frederick Sanger','male','Chemistry',1980);
INSERT INTO "nobels" VALUES ('Paul Berg','male','Chemistry',1980);
INSERT INTO "nobels" VALUES ('Walter Gilbert','male','Chemistry',1980);
INSERT INTO "nobels" VALUES ('Herta Müller','female','Literature',2009);
INSERT INTO "nobels" VALUES ('Earl W. Sutherland, Jr.','male','Physiology_or_Medicine',1971);
INSERT INTO "nobels" VALUES ('Eric Betzig','male','Chemistry',2014);
INSERT INTO "nobels" VALUES ('Stefan W. Hell','male','Chemistry',2014);
INSERT INTO "nobels" VALUES ('William E. Moerner','male','Chemistry',2014);
INSERT INTO "nobels" VALUES ('Otto Loewi','male','Physiology_or_Medicine',1936);
INSERT INTO "nobels" VALUES ('Sir Henry Hallett Dale','male','Physiology_or_Medicine',1936);
INSERT INTO "nobels" VALUES ('Howard Martin Temin','male','Physiology_or_Medicine',1975);
INSERT INTO "nobels" VALUES ('David Baltimore','male','Physiology_or_Medicine',1975);
INSERT INTO "nobels" VALUES ('Renato Dulbecco','male','Physiology_or_Medicine',1975);
INSERT INTO "nobels" VALUES ('Nelly Sachs','female','Literature',1966);
INSERT INTO "nobels" VALUES ('Shmuel Yosef Agnon','male','Literature',1966);
INSERT INTO "nobels" VALUES ('José Echegaray y Eizaguirre','male','Literature',1904);
INSERT INTO "nobels" VALUES ('Frédéric Mistral','male','Literature',1904);
INSERT INTO "nobels" VALUES ('Michael S. Brown','male','Physiology_or_Medicine',1985);
INSERT INTO "nobels" VALUES ('Joseph L. Goldstein','male','Physiology_or_Medicine',1985);
INSERT INTO "nobels" VALUES ('Joseph Brodsky','male','Literature',1987);
INSERT INTO "nobels" VALUES ('James P. Allison','male','Physiology_or_Medicine',2018);
INSERT INTO "nobels" VALUES ('Tasuku Honjo','male','Physiology_or_Medicine',2018);
INSERT INTO "nobels" VALUES ('Simon Kuznets','male','Economic_Sciences',1971);
INSERT INTO "nobels" VALUES ('Owen Willans Richardson','male','Physics',1928);
INSERT INTO "nobels" VALUES ('K. Alexander Müller','male','Physics',1987);
INSERT INTO "nobels" VALUES ('J. Georg Bednorz','male','Physics',1987);
INSERT INTO "nobels" VALUES ('Theodore William Richards','male','Chemistry',1914);
INSERT INTO "nobels" VALUES ('Tomas Tranströmer','male','Literature',2011);
INSERT INTO "nobels" VALUES ('Wole Soyinka','male','Literature',1986);
INSERT INTO "nobels" VALUES ('John Warcup Cornforth','male','Chemistry',1975);
INSERT INTO "nobels" VALUES ('Vladimir Prelog','male','Chemistry',1975);
INSERT INTO "nobels" VALUES ('Henry Taube','male','Chemistry',1983);
INSERT INTO "nobels" VALUES ('Eyvind Johnson','male','Literature',1974);
INSERT INTO "nobels" VALUES ('Harry Martinson','male','Literature',1974);
INSERT INTO "nobels" VALUES ('Willem Einthoven','male','Physiology_or_Medicine',1924);
INSERT INTO "nobels" VALUES ('Le Duc Tho','male','Peace',1973);
INSERT INTO "nobels" VALUES ('Henry Alfred Kissinger','male','Peace',1973);
INSERT INTO "nobels" VALUES ('Klas Pontus Arnoldson','male','Peace',1908);
INSERT INTO "nobels" VALUES ('Fredrik Bajer','male','Peace',1908);
INSERT INTO "nobels" VALUES ('Erwin Schrödinger','male','Physics',1933);
INSERT INTO "nobels" VALUES ('Paul Adrien Maurice Dirac','male','Physics',1933);
INSERT INTO "nobels" VALUES ('Mo Yan','male','Literature',2012);
INSERT INTO "nobels" VALUES ('Frits Zernike','male','Physics',1953);
INSERT INTO "nobels" VALUES ('Robert Bárány','male','Physiology_or_Medicine',1914);
INSERT INTO "nobels" VALUES ('John L. Hall','male','Physics',2005);
INSERT INTO "nobels" VALUES ('Theodor W. Hänsch','male','Physics',2005);
INSERT INTO "nobels" VALUES ('Roy J. Glauber','male','Physics',2005);
INSERT INTO "nobels" VALUES ('Torsten N. Wiesel','male','Physiology_or_Medicine',1981);
INSERT INTO "nobels" VALUES ('David H. Hubel','male','Physiology_or_Medicine',1981);
INSERT INTO "nobels" VALUES ('Roger W. Sperry','male','Physiology_or_Medicine',1981);
INSERT INTO "nobels" VALUES ('Paul Ehrlich','male','Physiology_or_Medicine',1908);
INSERT INTO "nobels" VALUES ('Ilya Ilyich Mechnikov','male','Physiology_or_Medicine',1908);
INSERT INTO "nobels" VALUES ('Henrik Pontoppidan','male','Literature',1917);
INSERT INTO "nobels" VALUES ('Karl Adolph Gjellerup','male','Literature',1917);
INSERT INTO "nobels" VALUES ('Isamu Akasaki','male','Physics',2014);
INSERT INTO "nobels" VALUES ('Shuji Nakamura','male','Physics',2014);
INSERT INTO "nobels" VALUES ('Hiroshi Amano','male','Physics',2014);
INSERT INTO "nobels" VALUES ('Rabindranath Tagore','male','Literature',1913);
INSERT INTO "nobels" VALUES ('Günter Grass','male','Literature',1999);
INSERT INTO "nobels" VALUES ('Susumu Tonegawa','male','Physiology_or_Medicine',1987);
INSERT INTO "nobels" VALUES ('Frederick Chapman Robbins','male','Physiology_or_Medicine',1954);
INSERT INTO "nobels" VALUES ('John Franklin Enders','male','Physiology_or_Medicine',1954);
INSERT INTO "nobels" VALUES ('Thomas Huckle Weller','male','Physiology_or_Medicine',1954);
INSERT INTO "nobels" VALUES ('Clinton Joseph Davisson','male','Physics',1937);
INSERT INTO "nobels" VALUES ('George Paget Thomson','male','Physics',1937);
INSERT INTO "nobels" VALUES ('Frédéric Joliot','male','Chemistry',1935);
INSERT INTO "nobels" VALUES ('Irène Joliot-Curie','female','Chemistry',1935);
INSERT INTO "nobels" VALUES ('James Chadwick','male','Physics',1935);
INSERT INTO "nobels" VALUES ('Léon Jouhaux','male','Peace',1951);
INSERT INTO "nobels" VALUES ('Elias James Corey','male','Chemistry',1990);
INSERT INTO "nobels" VALUES ('Konrad Lorenz','male','Physiology_or_Medicine',1973);
INSERT INTO "nobels" VALUES ('Nikolaas Tinbergen','male','Physiology_or_Medicine',1973);
INSERT INTO "nobels" VALUES ('Karl von Frisch','male','Physiology_or_Medicine',1973);
INSERT INTO "nobels" VALUES ('Julian Schwinger','male','Physics',1965);
INSERT INTO "nobels" VALUES ('Sin-Itiro Tomonaga','male','Physics',1965);
INSERT INTO "nobels" VALUES ('Richard P. Feynman','male','Physics',1965);
INSERT INTO "nobels" VALUES ('John C. Polanyi','male','Chemistry',1986);
INSERT INTO "nobels" VALUES ('Dudley R. Herschbach','male','Chemistry',1986);
INSERT INTO "nobels" VALUES ('Yuan T. Lee','male','Chemistry',1986);
INSERT INTO "nobels" VALUES ('Johannes Andreas Grib Fibiger','male','Physiology_or_Medicine',1926);
INSERT INTO "nobels" VALUES ('Rodney R. Porter','male','Physiology_or_Medicine',1972);
INSERT INTO "nobels" VALUES ('Gerald M. Edelman','male','Physiology_or_Medicine',1972);
INSERT INTO "nobels" VALUES ('Harald zur Hausen','male','Physiology_or_Medicine',2008);
INSERT INTO "nobels" VALUES ('Luc Montagnier','male','Physiology_or_Medicine',2008);
INSERT INTO "nobels" VALUES ('Françoise Barré-Sinoussi','female','Physiology_or_Medicine',2008);
INSERT INTO "nobels" VALUES ('Gregg L. Semenza','male','Physiology_or_Medicine',2019);
INSERT INTO "nobels" VALUES ('Sir Peter J. Ratcliffe','male','Physiology_or_Medicine',2019);
INSERT INTO "nobels" VALUES ('William G. Kaelin Jr','male','Physiology_or_Medicine',2019);
INSERT INTO "nobels" VALUES ('Enrico Fermi','male','Physics',1938);
INSERT INTO "nobels" VALUES ('John Boyd Orr, Baron Boyd-Orr of Brechin Mearn','male','Peace',1949);
INSERT INTO "nobels" VALUES ('Reinhard Selten','male','Economic_Sciences',1994);
INSERT INTO "nobels" VALUES ('John C. Harsanyi','male','Economic_Sciences',1994);
INSERT INTO "nobels" VALUES ('John F. Nash Jr.','male','Economic_Sciences',1994);
INSERT INTO "nobels" VALUES ('Owen Chamberlain','male','Physics',1959);
INSERT INTO "nobels" VALUES ('Emilio Gino Segrè','male','Physics',1959);
INSERT INTO "nobels" VALUES ('Kofi Atta Annan','male','Peace',2001);
INSERT INTO "nobels" VALUES ('Thomas R. Cech','male','Chemistry',1989);
INSERT INTO "nobels" VALUES ('Sidney Altman','male','Chemistry',1989);
INSERT INTO "nobels" VALUES ('Francis William Aston','male','Chemistry',1922);
INSERT INTO "nobels" VALUES ('Peter C. Doherty','male','Physiology_or_Medicine',1996);
INSERT INTO "nobels" VALUES ('Rolf M. Zinkernagel','male','Physiology_or_Medicine',1996);
INSERT INTO "nobels" VALUES ('Roger Y. Tsien','male','Chemistry',2008);
INSERT INTO "nobels" VALUES ('Osamu Shimomura','male','Chemistry',2008);
INSERT INTO "nobels" VALUES ('Martin Chalfie','male','Chemistry',2008);
INSERT INTO "nobels" VALUES ('Naguib Mahfouz','male','Literature',1988);
INSERT INTO "nobels" VALUES ('Richard R. Schrock','male','Chemistry',2005);
INSERT INTO "nobels" VALUES ('Robert H. Grubbs','male','Chemistry',2005);
INSERT INTO "nobels" VALUES ('Yves Chauvin','male','Chemistry',2005);
INSERT INTO "nobels" VALUES ('Melvin Calvin','male','Chemistry',1961);
INSERT INTO "nobels" VALUES ('Jean Baptiste Perrin','male','Physics',1926);
INSERT INTO "nobels" VALUES ('Otto Paul Hermann Diels','male','Chemistry',1950);
INSERT INTO "nobels" VALUES ('Kurt Alder','male','Chemistry',1950);
INSERT INTO "nobels" VALUES ('Il´ja Mikhailovich Frank','male','Physics',1958);
INSERT INTO "nobels" VALUES ('Pavel Alekseyevich Cherenkov','male','Physics',1958);
INSERT INTO "nobels" VALUES ('Igor Yevgenyevich Tamm','male','Physics',1958);
INSERT INTO "nobels" VALUES ('Philipp Eduard Anton von Lenard','male','Physics',1905);
INSERT INTO "nobels" VALUES ('Edward C. Prescott','male','Economic_Sciences',2004);
INSERT INTO "nobels" VALUES ('Finn E. Kydland','male','Economic_Sciences',2004);
INSERT INTO "nobels" VALUES ('Jack Steinberger','male','Physics',1988);
INSERT INTO "nobels" VALUES ('Leon M. Lederman','male','Physics',1988);
INSERT INTO "nobels" VALUES ('Melvin Schwartz','male','Physics',1988);
INSERT INTO "nobels" VALUES ('Daniel Bovet','male','Physiology_or_Medicine',1957);
INSERT INTO "nobels" VALUES ('William F. Sharpe','male','Economic_Sciences',1990);
INSERT INTO "nobels" VALUES ('Merton H. Miller','male','Economic_Sciences',1990);
INSERT INTO "nobels" VALUES ('Harry M. Markowitz','male','Economic_Sciences',1990);
INSERT INTO "nobels" VALUES ('Liu Xiaobo','male','Peace',2010);
INSERT INTO "nobels" VALUES ('Hermann Joseph Muller','male','Physiology_or_Medicine',1946);
INSERT INTO "nobels" VALUES ('Pär Fabian Lagerkvist','male','Literature',1951);
INSERT INTO "nobels" VALUES ('Gerhart Johann Robert Hauptmann','male','Literature',1912);
INSERT INTO "nobels" VALUES ('Richard Martin Willstätter','male','Chemistry',1915);
INSERT INTO "nobels" VALUES ('Saul Bellow','male','Literature',1976);
INSERT INTO "nobels" VALUES ('Sir Vidiadhar Surajprasad Naipaul','male','Literature',2001);
INSERT INTO "nobels" VALUES ('Lester Bowles Pearson','male','Peace',1957);
INSERT INTO "nobels" VALUES ('Donald Arthur Glaser','male','Physics',1960);
INSERT INTO "nobels" VALUES ('Cordell Hull','male','Peace',1945);
INSERT INTO "nobels" VALUES ('James E. Rothman','male','Physiology_or_Medicine',2013);
INSERT INTO "nobels" VALUES ('Randy W. Schekman','male','Physiology_or_Medicine',2013);
INSERT INTO "nobels" VALUES ('Thomas C. Südhof','male','Physiology_or_Medicine',2013);
INSERT INTO "nobels" VALUES ('Muhammad Yunus','male','Peace',2006);
INSERT INTO "nobels" VALUES ('David J. Wineland','male','Physics',2012);
INSERT INTO "nobels" VALUES ('Serge Haroche','male','Physics',2012);
INSERT INTO "nobels" VALUES ('Ronald Ross','male','Physiology_or_Medicine',1902);
INSERT INTO "nobels" VALUES ('Léon Victor Auguste Bourgeois','male','Peace',1920);
INSERT INTO "nobels" VALUES ('Fridtjof Nansen','male','Peace',1922);
INSERT INTO "nobels" VALUES ('Gerardus ''t Hooft','male','Physics',1999);
INSERT INTO "nobels" VALUES ('Martinus J.G. Veltman','male','Physics',1999);
INSERT INTO "nobels" VALUES ('Eugene Paul Wigner','male','Physics',1963);
INSERT INTO "nobels" VALUES ('Maria Goeppert Mayer','female','Physics',1963);
INSERT INTO "nobels" VALUES ('J. Hans D. Jensen','male','Physics',1963);
INSERT INTO "nobels" VALUES ('Vernon L. Smith','male','Economic_Sciences',2002);
INSERT INTO "nobels" VALUES ('Daniel Kahneman','male','Economic_Sciences',2002);
INSERT INTO "nobels" VALUES ('Rudolph A. Marcus','male','Chemistry',1992);
INSERT INTO "nobels" VALUES ('Philip J. Noel-Baker','male','Peace',1959);
INSERT INTO "nobels" VALUES ('William Alfred Fowler','male','Physics',1983);
INSERT INTO "nobels" VALUES ('Subramanyan Chandrasekhar','male','Physics',1983);
INSERT INTO "nobels" VALUES ('Elihu Root','male','Peace',1912);
INSERT INTO "nobels" VALUES ('Giosuè Carducci','male','Literature',1906);
INSERT INTO "nobels" VALUES ('Gerhard Domagk','male','Physiology_or_Medicine',1939);
INSERT INTO "nobels" VALUES ('Kailash Satyarthi','male','Peace',2014);
INSERT INTO "nobels" VALUES ('Malala Yousafzai','female','Peace',2014);
INSERT INTO "nobels" VALUES ('Sinclair Lewis','male','Literature',1930);
INSERT INTO "nobels" VALUES ('Didier Queloz','male','Physics',2019);
INSERT INTO "nobels" VALUES ('James Peebles','male','Physics',2019);
INSERT INTO "nobels" VALUES ('Michel Mayor','male','Physics',2019);
INSERT INTO "nobels" VALUES ('Hans Albrecht Bethe','male','Physics',1967);
INSERT INTO "nobels" VALUES ('Nils Gustaf Dalén','male','Physics',1912);
INSERT INTO "nobels" VALUES ('Eugenio Montale','male','Literature',1975);
INSERT INTO "nobels" VALUES ('Sir Norman Angell (Ralph Lane)','male','Peace',1933);
INSERT INTO "nobels" VALUES ('Hermann Staudinger','male','Chemistry',1953);
INSERT INTO "nobels" VALUES ('Czeslaw Milosz','male','Literature',1980);
INSERT INTO "nobels" VALUES ('Phillip A. Sharp','male','Physiology_or_Medicine',1993);
INSERT INTO "nobels" VALUES ('Richard J. Roberts','male','Physiology_or_Medicine',1993);
INSERT INTO "nobels" VALUES ('Lord Rayleigh (John William Strutt)','male','Physics',1904);
INSERT INTO "nobels" VALUES ('Mohamed ElBaradei','male','Peace',2005);
INSERT INTO "nobels" VALUES ('François Englert','male','Physics',2013);
INSERT INTO "nobels" VALUES ('Peter W. Higgs','male','Physics',2013);
INSERT INTO "nobels" VALUES ('Emil Theodor Kocher','male','Physiology_or_Medicine',1909);
INSERT INTO "nobels" VALUES ('Marie Curie, née Sklodowska','female','Chemistry',1911);
INSERT INTO "nobels" VALUES ('George Wald','male','Physiology_or_Medicine',1967);
INSERT INTO "nobels" VALUES ('Haldan Keffer Hartline','male','Physiology_or_Medicine',1967);
INSERT INTO "nobels" VALUES ('Ragnar Granit','male','Physiology_or_Medicine',1967);
INSERT INTO "nobels" VALUES ('Willy Brandt','male','Peace',1971);
INSERT INTO "nobels" VALUES ('Douglas D. Osheroff','male','Physics',1996);
INSERT INTO "nobels" VALUES ('Robert C. Richardson','male','Physics',1996);
INSERT INTO "nobels" VALUES ('David M. Lee','male','Physics',1996);
INSERT INTO "nobels" VALUES ('Mikhail Sergeyevich Gorbachev','male','Peace',1990);
INSERT INTO "nobels" VALUES ('Russell A. Hulse','male','Physics',1993);
INSERT INTO "nobels" VALUES ('Joseph H. Taylor Jr.','male','Physics',1993);
INSERT INTO "nobels" VALUES ('Trygve Haavelmo','male','Economic_Sciences',1989);
INSERT INTO "nobels" VALUES ('Ernst Boris Chain','male','Physiology_or_Medicine',1945);
INSERT INTO "nobels" VALUES ('Sir Alexander Fleming','male','Physiology_or_Medicine',1945);
INSERT INTO "nobels" VALUES ('Sir Howard Walter Florey','male','Physiology_or_Medicine',1945);
INSERT INTO "nobels" VALUES ('John C. Mather','male','Physics',2006);
INSERT INTO "nobels" VALUES ('George F. Smoot','male','Physics',2006);
INSERT INTO "nobels" VALUES ('Robert Burns Woodward','male','Chemistry',1965);
INSERT INTO "nobels" VALUES ('Svante August Arrhenius','male','Chemistry',1903);
INSERT INTO "nobels" VALUES ('Thomas Woodrow Wilson','male','Peace',1919);
INSERT INTO "nobels" VALUES ('John Cowdery Kendrew','male','Chemistry',1962);
INSERT INTO "nobels" VALUES ('Max Ferdinand Perutz','male','Chemistry',1962);
INSERT INTO "nobels" VALUES ('Jan Tinbergen','male','Economic_Sciences',1969);
INSERT INTO "nobels" VALUES ('Ragnar Frisch','male','Economic_Sciences',1969);
INSERT INTO "nobels" VALUES ('Corneille Jean François Heymans','male','Physiology_or_Medicine',1938);
INSERT INTO "nobels" VALUES ('Tadeus Reichstein','male','Physiology_or_Medicine',1950);
INSERT INTO "nobels" VALUES ('Edward Calvin Kendall','male','Physiology_or_Medicine',1950);
INSERT INTO "nobels" VALUES ('Philip Showalter Hench','male','Physiology_or_Medicine',1950);
INSERT INTO "nobels" VALUES ('Stanley B. Prusiner','male','Physiology_or_Medicine',1997);
INSERT INTO "nobels" VALUES ('Imre Kertész','male','Literature',2002);
INSERT INTO "nobels" VALUES ('Sir John Douglas Cockcroft','male','Physics',1951);
INSERT INTO "nobels" VALUES ('Ernest Thomas Sinton Walton','male','Physics',1951);
INSERT INTO "nobels" VALUES ('Max Karl Ernst Ludwig Planck','male','Physics',1918);
INSERT INTO "nobels" VALUES ('Günter Blobel','male','Physiology_or_Medicine',1999);
INSERT INTO "nobels" VALUES ('James Tobin','male','Economic_Sciences',1981);
INSERT INTO "nobels" VALUES ('Heinrich Otto Wieland','male','Chemistry',1927);
INSERT INTO "nobels" VALUES ('Gustav Ludwig Hertz','male','Physics',1925);
INSERT INTO "nobels" VALUES ('James Franck','male','Physics',1925);
INSERT INTO "nobels" VALUES ('Rigoberta Menchú Tum','female','Peace',1992);
INSERT INTO "nobels" VALUES ('Edgar Algernon Robert Gascoyne-Cecil, 1st Viscount Cecil of Chelwood','male','Peace',1937);
INSERT INTO "nobels" VALUES ('Henry W. Kendall','male','Physics',1990);
INSERT INTO "nobels" VALUES ('Jerome I. Friedman','male','Physics',1990);
INSERT INTO "nobels" VALUES ('Richard E. Taylor','male','Physics',1990);
INSERT INTO "nobels" VALUES ('Niels Henrik David Bohr','male','Physics',1922);
INSERT INTO "nobels" VALUES ('Frederick Soddy','male','Chemistry',1921);
INSERT INTO "nobels" VALUES ('Ernest Rutherford','male','Chemistry',1908);
INSERT INTO "nobels" VALUES ('Octavio Paz','male','Literature',1990);
INSERT INTO "nobels" VALUES ('Glenn Theodore Seaborg','male','Chemistry',1951);
INSERT INTO "nobels" VALUES ('Edwin Mattison McMillan','male','Chemistry',1951);
INSERT INTO "nobels" VALUES ('Carl Gustaf Verner von Heidenstam','male','Literature',1916);
INSERT INTO "nobels" VALUES ('Jean-Paul Sartre','male','Literature',1964);
INSERT INTO "nobels" VALUES ('David Trimble','male','Peace',1998);
INSERT INTO "nobels" VALUES ('John Hume','male','Peace',1998);
INSERT INTO "nobels" VALUES ('Milton Friedman','male','Economic_Sciences',1976);
INSERT INTO "nobels" VALUES ('Robert C. Merton','male','Economic_Sciences',1997);
INSERT INTO "nobels" VALUES ('Myron S. Scholes','male','Economic_Sciences',1997);
INSERT INTO "nobels" VALUES ('Louise Glück','female','Literature',2020);
INSERT INTO "nobels" VALUES ('Lawrence R. Klein','male','Economic_Sciences',1980);
INSERT INTO "nobels" VALUES ('Irving Langmuir','male','Chemistry',1932);
INSERT INTO "nobels" VALUES ('J. Michael Kosterlitz','male','Physics',2016);
INSERT INTO "nobels" VALUES ('David J. Thouless','male','Physics',2016);
INSERT INTO "nobels" VALUES ('F. Duncan M. Haldane','male','Physics',2016);
INSERT INTO "nobels" VALUES ('Pablo Neruda','male','Literature',1971);
INSERT INTO "nobels" VALUES ('John Steinbeck','male','Literature',1962);
INSERT INTO "nobels" VALUES ('Lars Olof Jonathan (Nathan) Söderblom','male','Peace',1930);
INSERT INTO "nobels" VALUES ('Luigi Pirandello','male','Literature',1934);
INSERT INTO "nobels" VALUES ('Fritz Pregl','male','Chemistry',1923);
INSERT INTO "nobels" VALUES ('Ronald H. Coase','male','Economic_Sciences',1991);
INSERT INTO "nobels" VALUES ('William Faulkner','male','Literature',1949);
INSERT INTO "nobels" VALUES ('Edward Mills Purcell','male','Physics',1952);
INSERT INTO "nobels" VALUES ('Felix Bloch','male','Physics',1952);
INSERT INTO "nobels" VALUES ('Georg von Békésy','male','Physiology_or_Medicine',1961);
INSERT INTO "nobels" VALUES ('Dennis Gabor','male','Physics',1971);
INSERT INTO "nobels" VALUES ('Robert M. Solow','male','Economic_Sciences',1987);
INSERT INTO "nobels" VALUES ('Gao Xingjian','male','Literature',2000);
INSERT INTO "nobels" VALUES ('Johannes Stark','male','Physics',1919);
INSERT INTO "nobels" VALUES ('Oscar Arias Sánchez','male','Peace',1987);
INSERT INTO "nobels" VALUES ('Juan Ramón Jiménez','male','Literature',1956);
INSERT INTO "nobels" VALUES ('Juan Manuel Santos','male','Peace',2016);
INSERT INTO "nobels" VALUES ('Otto Hahn','male','Chemistry',1944);
INSERT INTO "nobels" VALUES ('Herbert A. Hauptman','male','Chemistry',1985);
INSERT INTO "nobels" VALUES ('Jerome Karle','male','Chemistry',1985);
INSERT INTO "nobels" VALUES ('Jaroslav Seifert','male','Literature',1984);
INSERT INTO "nobels" VALUES ('Hans Fischer','male','Chemistry',1930);
INSERT INTO "nobels" VALUES ('Gerard Debreu','male','Economic_Sciences',1983);
INSERT INTO "nobels" VALUES ('Jeffrey C. Hall','male','Physiology_or_Medicine',2017);
INSERT INTO "nobels" VALUES ('Michael W. Young','male','Physiology_or_Medicine',2017);
INSERT INTO "nobels" VALUES ('Michael Rosbash','male','Physiology_or_Medicine',2017);
INSERT INTO "nobels" VALUES ('Desmond Mpilo Tutu','male','Peace',1984);
INSERT INTO "nobels" VALUES ('Hannes Olof Gösta Alfvén','male','Physics',1970);
INSERT INTO "nobels" VALUES ('Louis Eugène Félix Néel','male','Physics',1970);
INSERT INTO "nobels" VALUES ('Erik Axel Karlfeldt','male','Literature',1931);
INSERT INTO "nobels" VALUES ('Ernst Otto Fischer','male','Chemistry',1973);
INSERT INTO "nobels" VALUES ('Geoffrey Wilkinson','male','Chemistry',1973);
INSERT INTO "nobels" VALUES ('Patrick Modiano','male','Literature',2014);
INSERT INTO "nobels" VALUES ('Emmanuelle Charpentier','female','Chemistry',2020);
INSERT INTO "nobels" VALUES ('Jennifer A. Doudna','female','Chemistry',2020);
INSERT INTO "nobels" VALUES ('Dan Shechtman','male','Chemistry',2011);
INSERT INTO "nobels" VALUES ('Emily Greene Balch','female','Peace',1946);
INSERT INTO "nobels" VALUES ('John Raleigh Mott','male','Peace',1946);
INSERT INTO "nobels" VALUES ('Sigrid Undset','female','Literature',1928);
INSERT INTO "nobels" VALUES ('Wassily Wassilyevich Leontief','male','Economic_Sciences',1973);
INSERT INTO "nobels" VALUES ('Wladyslaw Stanislaw Reymont','male','Literature',1924);
INSERT INTO "nobels" VALUES ('Thomas Stearns Eliot','male','Literature',1948);
INSERT INTO "nobels" VALUES ('Eugene Gladstone O''Neill','male','Literature',1936);
INSERT INTO "nobels" VALUES ('Robert S. Mulliken','male','Chemistry',1966);
INSERT INTO "nobels" VALUES ('Paul Sabatier','male','Chemistry',1912);
INSERT INTO "nobels" VALUES ('Victor Grignard','male','Chemistry',1912);
INSERT INTO "nobels" VALUES ('Max von Laue','male','Physics',1914);
INSERT INTO "nobels" VALUES ('William Golding','male','Literature',1983);
INSERT INTO "nobels" VALUES ('Giorgos Seferis','male','Literature',1963);
INSERT INTO "nobels" VALUES ('Olga Tokarczuk','female','Literature',2018);
INSERT INTO "nobels" VALUES ('Manfred Eigen','male','Chemistry',1967);
INSERT INTO "nobels" VALUES ('George Porter','male','Chemistry',1967);
INSERT INTO "nobels" VALUES ('Ronald George Wreyford Norrish','male','Chemistry',1967);
INSERT INTO "nobels" VALUES ('Daniel L. McFadden','male','Economic_Sciences',2000);
INSERT INTO "nobels" VALUES ('James J. Heckman','male','Economic_Sciences',2000);
INSERT INTO "nobels" VALUES ('Romain Rolland','male','Literature',1915);
INSERT INTO "nobels" VALUES ('Paul Krugman','male','Economic_Sciences',2008);
INSERT INTO "nobels" VALUES ('Joseph John Thomson','male','Physics',1906);
INSERT INTO "nobels" VALUES ('Douglass C. North','male','Economic_Sciences',1993);
INSERT INTO "nobels" VALUES ('Robert W. Fogel','male','Economic_Sciences',1993);
INSERT INTO "nobels" VALUES ('Sir William Ramsay','male','Chemistry',1904);
INSERT INTO "nobels" VALUES ('Joshua Lederberg','male','Physiology_or_Medicine',1958);
INSERT INTO "nobels" VALUES ('Edward Lawrie Tatum','male','Physiology_or_Medicine',1958);
INSERT INTO "nobels" VALUES ('George Wells Beadle','male','Physiology_or_Medicine',1958);
INSERT INTO "nobels" VALUES ('Jaroslav Heyrovsky','male','Chemistry',1959);
INSERT INTO "nobels" VALUES ('Julius Wagner-Jauregg','male','Physiology_or_Medicine',1927);
INSERT INTO "nobels" VALUES ('Wislawa Szymborska','female','Literature',1996);
INSERT INTO "nobels" VALUES ('Yasunari Kawabata','male','Literature',1968);
INSERT INTO "nobels" VALUES ('James Earl Carter','male','Peace',2002);
INSERT INTO "nobels" VALUES ('Hans Spemann','male','Physiology_or_Medicine',1935);
INSERT INTO "nobels" VALUES ('Lars Onsager','male','Chemistry',1968);
INSERT INTO "nobels" VALUES ('Georg Wittig','male','Chemistry',1979);
INSERT INTO "nobels" VALUES ('Herbert C. Brown','male','Chemistry',1979);
INSERT INTO "nobels" VALUES ('The 14th Dalai Lama (Tenzin Gyatso)','male','Peace',1989);
INSERT INTO "nobels" VALUES ('Franco Modigliani','male','Economic_Sciences',1985);
INSERT INTO "nobels" VALUES ('Horst L. Störmer','male','Physics',1998);
INSERT INTO "nobels" VALUES ('Daniel C. Tsui','male','Physics',1998);
INSERT INTO "nobels" VALUES ('Robert B. Laughlin','male','Physics',1998);
INSERT INTO "nobels" VALUES ('Saint-John Perse','male','Literature',1960);
INSERT INTO "nobels" VALUES ('Gerhard Ertl','male','Chemistry',2007);
INSERT INTO "nobels" VALUES ('Gerhard Herzberg','male','Chemistry',1971);
INSERT INTO "nobels" VALUES ('Jean-Marie Gustave Le Clézio','male','Literature',2008);
INSERT INTO "nobels" VALUES ('William Butler Yeats','male','Literature',1923);
INSERT INTO "nobels" VALUES ('Peter D. Mitchell','male','Chemistry',1978);
INSERT INTO "nobels" VALUES ('Patrick Maynard Stuart Blackett','male','Physics',1948);
INSERT INTO "nobels" VALUES ('Nadine Gordimer','female','Literature',1991);
INSERT INTO "nobels" VALUES ('Frederik Willem de Klerk','male','Peace',1993);
INSERT INTO "nobels" VALUES ('Nelson Rolihlahla Mandela','male','Peace',1993);
INSERT INTO "nobels" VALUES ('Edward Adelbert Doisy','male','Physiology_or_Medicine',1943);
INSERT INTO "nobels" VALUES ('Henrik Carl Peter Dam','male','Physiology_or_Medicine',1943);
INSERT INTO "nobels" VALUES ('Luis F. Leloir','male','Chemistry',1970);
INSERT INTO "nobels" VALUES ('William D. Nordhaus','male','Economic_Sciences',2018);
INSERT INTO "nobels" VALUES ('Paul M. Romer','male','Economic_Sciences',2018);
INSERT INTO "nobels" VALUES ('Fritz Haber','male','Chemistry',1918);
INSERT INTO "nobels" VALUES ('Walter Kohn','male','Chemistry',1998);
INSERT INTO "nobels" VALUES ('John A. Pople','male','Chemistry',1998);
INSERT INTO "nobels" VALUES ('Maurice Allais','male','Economic_Sciences',1988);
INSERT INTO "nobels" VALUES ('Johannes Vilhelm Jensen','male','Literature',1944);
INSERT INTO "nobels" VALUES ('George Catlett Marshall','male','Peace',1953);
INSERT INTO "nobels" VALUES ('Robert A. Mundell','male','Economic_Sciences',1999);
INSERT INTO "nobels" VALUES ('Herbert A. Simon','male','Economic_Sciences',1978);
INSERT INTO "nobels" VALUES ('Jules Bordet','male','Physiology_or_Medicine',1919);
INSERT INTO "nobels" VALUES ('Pearl Buck','female','Literature',1938);
INSERT INTO "nobels" VALUES ('Ilya Romanovich Prigogine','male','Chemistry',1977);
INSERT INTO "nobels" VALUES ('Toni Morrison','female','Literature',1993);
INSERT INTO "nobels" VALUES ('Kim Dae-jung','male','Peace',2000);
INSERT INTO "nobels" VALUES ('Edgar Douglas Adrian','male','Physiology_or_Medicine',1932);
INSERT INTO "nobels" VALUES ('Sir Charles Scott Sherrington','male','Physiology_or_Medicine',1932);
INSERT INTO "nobels" VALUES ('Louis J. Ignarro','male','Physiology_or_Medicine',1998);
INSERT INTO "nobels" VALUES ('Ferid Murad','male','Physiology_or_Medicine',1998);
INSERT INTO "nobels" VALUES ('Robert F. Furchgott','male','Physiology_or_Medicine',1998);
INSERT INTO "nobels" VALUES ('Paul J. Flory','male','Chemistry',1974);
INSERT INTO "nobels" VALUES ('Henri Bergson','male','Literature',1927);
INSERT INTO "nobels" VALUES ('Jacinto Benavente','male','Literature',1922);
INSERT INTO "nobels" VALUES ('Mother Teresa','female','Peace',1979);
INSERT INTO "nobels" VALUES ('Rudolf Christoph Eucken','male','Literature',1908);
INSERT INTO "nobels" VALUES ('Max Theiler','male','Physiology_or_Medicine',1951);
INSERT INTO "nobels" VALUES ('Linus Carl Pauling','male','Peace',1962);
INSERT INTO "nobels" VALUES ('Linus Carl Pauling','male','Chemistry',1954);
INSERT INTO "nobels" VALUES ('Patrick White','male','Literature',1973);
INSERT INTO "nobels" VALUES ('Ernest Miller Hemingway','male','Literature',1954);
INSERT INTO "nobels" VALUES ('Karl Manne Georg Siegbahn','male','Physics',1924);
INSERT INTO "nobels" VALUES ('Richard R. Ernst','male','Chemistry',1991);
INSERT INTO "nobels" VALUES ('Werner Karl Heisenberg','male','Physics',1932);
INSERT INTO "nobels" VALUES ('Edwin G. Krebs','male','Physiology_or_Medicine',1992);
INSERT INTO "nobels" VALUES ('Edmond H. Fischer','male','Physiology_or_Medicine',1992);
INSERT INTO "nobels" VALUES ('Isaac Bashevis Singer','male','Literature',1978);
INSERT INTO "nobels" VALUES ('Robert Koch','male','Physiology_or_Medicine',1905);
INSERT INTO "nobels" VALUES ('Wendell Meredith Stanley','male','Chemistry',1946);
INSERT INTO "nobels" VALUES ('James Batcheller Sumner','male','Chemistry',1946);
INSERT INTO "nobels" VALUES ('John Howard Northrop','male','Chemistry',1946);
INSERT INTO "nobels" VALUES ('Edmund S. Phelps','male','Economic_Sciences',2006);
INSERT INTO "nobels" VALUES ('Robert E. Lucas Jr.','male','Economic_Sciences',1995);
INSERT INTO "nobels" VALUES ('Samuel Beckett','male','Literature',1969);
INSERT INTO "nobels" VALUES ('Otto Stern','male','Physics',1943);
INSERT INTO "nobels" VALUES ('John M. Coetzee','male','Literature',2003);
INSERT INTO "nobels" VALUES ('Henri Moissan','male','Chemistry',1906);
INSERT INTO "nobels" VALUES ('Paul Johann Ludwig Heyse','male','Literature',1910);
INSERT INTO "nobels" VALUES ('Gabriel Lippmann','male','Physics',1908);
INSERT INTO "nobels" VALUES ('Roger D. Kornberg','male','Chemistry',2006);
INSERT INTO "nobels" VALUES ('Norman Ernest Borlaug','male','Peace',1970);
INSERT INTO "nobels" VALUES ('Seamus Heaney','male','Literature',1995);
INSERT INTO "nobels" VALUES ('Richard Stone','male','Economic_Sciences',1984);
INSERT INTO "nobels" VALUES ('James M. Buchanan Jr.','male','Economic_Sciences',1986);
INSERT INTO "nobels" VALUES ('Sir Chandrasekhara Venkata Raman','male','Physics',1930);
INSERT INTO "nobels" VALUES ('Walther Hermann Nernst','male','Chemistry',1920);
INSERT INTO "nobels" VALUES ('Dario Fo','male','Literature',1997);
INSERT INTO "nobels" VALUES ('William N. Lipscomb','male','Chemistry',1976);
INSERT INTO "nobels" VALUES ('Richard H. Thaler','male','Economic_Sciences',2017);
INSERT INTO "nobels" VALUES ('Jean Tirole','male','Economic_Sciences',2014);
INSERT INTO "nobels" VALUES ('Wangari Muta Maathai','female','Peace',2004);
INSERT INTO "nobels" VALUES ('Paul A. Samuelson','male','Economic_Sciences',1970);
INSERT INTO "nobels" VALUES ('José Saramago','male','Literature',1998);
INSERT INTO "nobels" VALUES ('Hermann Hesse','male','Literature',1946);
INSERT INTO "nobels" VALUES ('Martti Ahtisaari','male','Peace',2008);
INSERT INTO "nobels" VALUES ('Aung San Suu Kyi','female','Peace',1991);
INSERT INTO "nobels" VALUES ('Peter Handke','male','Literature',2019);
INSERT INTO "nobels" VALUES ('Yoshinori Ohsumi','male','Physiology_or_Medicine',2016);
INSERT INTO "nobels" VALUES ('Percy Williams Bridgman','male','Physics',1946);
INSERT INTO "nobels" VALUES ('Mikhail Aleksandrovich Sholokhov','male','Literature',1965);
INSERT INTO "nobels" VALUES ('Frans Eemil Sillanpää','male','Literature',1939);
INSERT INTO "nobels" VALUES ('Louis Renault','male','Peace',1907);
INSERT INTO "nobels" VALUES ('Ernesto Teodoro Moneta','male','Peace',1907);
INSERT INTO "nobels" VALUES ('Robert Andrews Millikan','male','Physics',1923);
INSERT INTO "nobels" VALUES ('Sir Winston Leonard Spencer Churchill','male','Literature',1953);
INSERT INTO "nobels" VALUES ('Halldór Kiljan Laxness','male','Literature',1955);
INSERT INTO "nobels" VALUES ('Prince Louis-Victor Pierre Raymond de Broglie','male','Physics',1929);
INSERT INTO "nobels" VALUES ('Miguel Angel Asturias','male','Literature',1967);
INSERT INTO "nobels" VALUES ('Pierre-Gilles de Gennes','male','Physics',1991);
INSERT INTO "nobels" VALUES ('Vincent du Vigneaud','male','Chemistry',1955);
INSERT INTO "nobels" VALUES ('Frederick Reines','male','Physics',1995);
INSERT INTO "nobels" VALUES ('Martin L. Perl','male','Physics',1995);
INSERT INTO "nobels" VALUES ('George de Hevesy','male','Chemistry',1943);
INSERT INTO "nobels" VALUES ('Ivan Petrovich Pavlov','male','Physiology_or_Medicine',1904);
INSERT INTO "nobels" VALUES ('Wolfgang Pauli','male','Physics',1945);
INSERT INTO "nobels" VALUES ('Hideki Yukawa','male','Physics',1949);
INSERT INTO "nobels" VALUES ('Jacobus Henricus van ''t Hoff','male','Chemistry',1901);
INSERT INTO "nobels" VALUES ('Lech Walesa','male','Peace',1983);
INSERT INTO "nobels" VALUES ('Odysseus Elytis','male','Literature',1979);
INSERT INTO "nobels" VALUES ('Willard Frank Libby','male','Chemistry',1960);
INSERT INTO "nobels" VALUES ('Roger Martin du Gard','male','Literature',1937);
INSERT INTO "nobels" VALUES ('Ardem Patapoutian','male','Physiology_or_Medicine',2021);
INSERT INTO "nobels" VALUES ('David Julius','male','Physiology_or_Medicine',2021);
INSERT INTO "nobels" VALUES ('Benjamin List','male','Chemistry',2021);
INSERT INTO "nobels" VALUES ('David W.C. MacMillan','male','Chemistry',2021);
INSERT INTO "nobels" VALUES ('Giorgio Parisi','male','Physics',2021);
INSERT INTO "nobels" VALUES ('Klaus Hasselmann','male','Physics',2021);
INSERT INTO "nobels" VALUES ('Syukuro Manabe','male','Physics',2021);
INSERT INTO "nobels" VALUES ('David Card','male','Economic_Sciences',2021);
INSERT INTO "nobels" VALUES ('Guido W. Imbens','male','Economic_Sciences',2021);
INSERT INTO "nobels" VALUES ('Joshua D. Angrist','male','Economic_Sciences',2021);
INSERT INTO "nobels" VALUES ('Dmitry Andreyevich Muratov','male','Peace',2021);
INSERT INTO "nobels" VALUES ('Maria Ressa','female','Peace',2021);
INSERT INTO "nobels" VALUES ('Annie Ernaux','female','Literature',2022);
INSERT INTO "nobels" VALUES ('Ales Bialiatski','male','Peace',2022);
INSERT INTO "nobels" VALUES ('K. Barry Sharpless','male','Chemistry',2022);
INSERT INTO "nobels" VALUES ('Carolyn R. Bertozzi','female','Chemistry',2022);
INSERT INTO "nobels" VALUES ('Morten Meldal','male','Chemistry',2022);
INSERT INTO "nobels" VALUES ('Svante Pääbo','male','Physiology_or_Medicine',2022);
INSERT INTO "nobels" VALUES ('Narges Mohammadi','female','Peace',2023);
INSERT INTO "nobels" VALUES ('Jon Fosse','male','Literature',2023);
INSERT INTO "nobels" VALUES ('Pierre Agostini','male','Physics',2023);
INSERT INTO "nobels" VALUES ('Ferenc Krausz','male','Physics',2023);
INSERT INTO "nobels" VALUES ('Anne L’Huillier','female','Physics',2023);
INSERT INTO "nobels" VALUES ('Drew Weissman','male','Physiology_or_Medicine',2023);
INSERT INTO "nobels" VALUES ('Katalin Kariko','female','Physiology_or_Medicine',2023);
INSERT INTO "nobels" VALUES ('Claudia Golden','female','Economic_Sciences',2023);
INSERT INTO "nobels" VALUES ('Alexei Iekimov','male','Chemistry',2023);
INSERT INTO "nobels" VALUES ('Louis E. Brus','male','Chemistry',2023);
INSERT INTO "nobels" VALUES ('Moungi Bawendi','male','Chemistry',2023);
INSERT INTO "nobels" VALUES ('John J.Hopfield','male','Physics',2024);
INSERT INTO "nobels" VALUES ('Geoffrey Hinton','male','Physics',2024);
INSERT INTO "nobels" VALUES ('David Baker','male','Chemistry',2024);
INSERT INTO "nobels" VALUES ('Demis Hassabis','male','Chemistry',2024);
INSERT INTO "nobels" VALUES ('John Jumper','male','Chemistry',2024);
INSERT INTO "nobels" VALUES ('Victor Ambros','male','Physiology_or_Medicine',2024);
INSERT INTO "nobels" VALUES ('Gary Ruvkun','male','Physiology_or_Medicine',2024);
INSERT INTO "nobels" VALUES ('Han Kang','female','Literature',2024);
INSERT INTO "nobels" VALUES ('Nihon Hidankyo','male','Peace',2024);
INSERT INTO "nobels" VALUES ('Daron Acemoglu','male','Economic_Sciences',2024);
INSERT INTO "nobels" VALUES ('Simon Johnson','male','Economic_Sciences',2024);
INSERT INTO "nobels" VALUES ('James A.Robinson','male','Economic_Sciences',2024);
COMMIT;
